[WIP] Variables and types section
PumasAI-Labs/Julia-Workshop pull request #1
Opened 2023-05-17 21:46 UTC by jotas6

Setup and content for the Julia variables and types section of the workshop.

## Status
- [x] Edit the PLACEHOLDER text
- [x] Edit README file
- [x] Code examples
- [ ]  Instructor notes
- [ ] Reference sheet
- [ ] Schedule

2023-05-26 19:02 UTC, storopoli requested changes

2023-05-26 19:02 UTC, storopoli commented on docs/instructors.md
> +explain the use of `!` for negation, `||` for OR and `&&` for AND. Make sure to go over how these operators work if needed.
It's useful to add that some users might ask about single `|` and `?`. How the instructor would reply to that question?

2023-05-26 19:02 UTC, storopoli commented on docs/reference.md
>  ## Glossary
We are missing `Float`, `Int` etc.

2023-05-26 19:41 UTC, jotas6 commented on 01-variables/03-strings.jl
> +
Yes, I think that is much better

2023-05-26 19:53 UTC, jotas6 commented on docs/reference.md
>  ## Glossary
Would this be a description of the types? Something like this?

| Action | Command | Observations |
|-----------|-----------------|---------------------|
| Integer type | `Int` | |

2023-05-27 00:32 UTC, jotas6 commented
I think I have covered all the comments (except for the one where I left the question). I marked the conversations are resolved to keep track of what I was doing, but I could make more adjustments if the solutions are not good.

2023-06-01 20:05 UTC, storopoli commented on docs/reference.md
>  ## Glossary
Yes that would be good.

2023-06-01 20:05 UTC, storopoli approved these changes

2023-06-01 21:51 UTC, merged